version: '3.8'
services:
  app:
    container_name: cookunity_app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    links:
      - redis
    ports:
      - '8083:8080'
    environment:
      NODE_ENV: development
      PORT: 8080
  redis:
    image: redis
    volumes:
      - ./data:/data
    expose:
      - 6379
    ports:
      - '6379:6379'
