version: '3.9'

volumes:
  data:
    driver: local

services:
  app:
    container_name: cookunity_app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    links:
      - redis
    ports:
      - '8000:8080'
    environment:
      NODE_ENV: development
      PORT: 8080
      REDIS_PORT: 6379
      REDIS_URL: redis://redis
    # volumes:
    #   - ./:/app
    # stdin_open: true
    # tty: true

  redis:
    image: redis
    volumes:
      - ./data:/data
    expose:
      - 6379
    ports:
      - '6379:6379'
